{% set name = "geotiff" %}
{% set version = "0.2.9" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a14de2e170840c5a137c5047e47d6f5fca3e36df72843bd40ce91b234c1e505

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - tifffile >=2021.7.2,<2022.4.28
    - numpy
    - pyproj
    - zarr >=2.10.*

test:
  imports:
    - geotiff
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/KipCrossing/geotiff
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A noGDAL tool for reading geotiff files
  description: |
    Python-geotiff is a library that reads geotiff files without
    the need for GDAL, a program that was not built with Python in mind.
    "noGDAL" is a philosophy for developing geospatial programs in
    python without using GDAL and python-geotiff aims to provide a
    GDAL-less means of interfacing with geotiff files.
  dev_url: https://github.com/KipCrossing/geotiff

extra:
  recipe-maintainers:
    - KipCrossing
    - Zeitsperre
    - cehbrecht
