{% set name = "geotiff" %}
{% set version = "0.2.10" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 36da356d3e2f6e3719bad32212283fe99049373391c7f576c2d6022642ad88d6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tifffile >=2021.7.4,!=2022.4.28
    - numpy <2.0 # Deprecation requires changes: "module 'numpy' has no attribute 'product'"
    - pyproj
    - zarr >=2.12.0,<2.13

test:
  imports:
    - geotiff
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/KipCrossing/geotiff
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: A noGDAL tool for reading geotiff files
  description: |
    Python-geotiff is a library that reads geotiff files without
    the need for GDAL, a program that was not built with Python in mind.
    "noGDAL" is a philosophy for developing geospatial programs in
    python without using GDAL and python-geotiff aims to provide a
    GDAL-less means of interfacing with geotiff files.
  dev_url: https://github.com/KipCrossing/geotiff

extra:
  recipe-maintainers:
    - KipCrossing
    - Zeitsperre
    - cehbrecht
